kind: Service
apiVersion: v1
metadata:
  name: jersey0-service
  labels:
    app: jersey0
spec:
  type: NodePort
  selector:
    app: jersey0
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP


